# Generated by Django 6.0.6 on 2026-06-28 21:45

import datetime
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.comparison
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_posicion', models.CharField(max_length=80, unique=True)),
                ('abreviatura', models.CharField(blank=True, max_length=10, null=True)),
                ('zona', models.CharField(choices=[('Porteria', 'Porteria'), ('Defensa', 'Defensa'), ('Mediocampo', 'Mediocampo'), ('Ataque', 'Ataque')], max_length=20)),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciones',
                'db_table': 'posiciones',
                'ordering': ['zona', 'nombre_posicion'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('tipo_usuario', models.CharField(choices=[('Coach', 'Coach'), ('Scout', 'Scout'), ('Player', 'Player')], max_length=20)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Suspendido', 'Suspendido')], default='Activo', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('idioma', models.CharField(default='es', max_length=10)),
                ('unidad_medida', models.CharField(choices=[('Metrico', 'Metrico'), ('Imperial', 'Imperial')], default='Metrico', max_length=10)),
                ('notificaciones_activas', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_entidad', models.CharField(max_length=150)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(default='Ecuador', max_length=100)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'db_table': 'entidades',
                'ordering': ['nombre_entidad'],
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('edad_minima', models.SmallIntegerField(blank=True, null=True)),
                ('edad_maxima', models.SmallIntegerField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Mixto', 'Mixto')], default='Masculino', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='stats.entidad')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('foto_url', models.URLField(blank=True, max_length=500, null=True)),
                ('numero_camiseta', models.SmallIntegerField(blank=True, null=True)),
                ('pie_dominante', models.CharField(choices=[('Derecho', 'Derecho'), ('Izquierdo', 'Izquierdo'), ('Ambidiestro', 'Ambidiestro')], default='Derecho', max_length=15)),
                ('nacionalidad', models.CharField(blank=True, max_length=80, null=True)),
                ('documento_identidad', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Lesionado', 'Lesionado'), ('Suspendido', 'Suspendido'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='stats.categoria')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='stats.entidad')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'jugadores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='HistorialAntropometrico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grasa_corporal', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('masa_muscular', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('imc', models.GeneratedField(db_persist=True, expression=models.ExpressionWrapper(django.db.models.expressions.CombinedExpression(models.F('peso_kg'), '/', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('altura_cm'), '/', models.Value(100.0)), '*', django.db.models.expressions.CombinedExpression(models.F('altura_cm'), '/', models.Value(100.0)))), output_field=models.DecimalField(decimal_places=2, max_digits=5)), output_field=models.DecimalField(decimal_places=2, max_digits=5))),
                ('fecha_toma', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_antropometrico', to='stats.jugador')),
            ],
            options={
                'db_table': 'historial_antropometrico',
                'ordering': ['-fecha_toma'],
            },
        ),
        migrations.CreateModel(
            name='ContratoInterno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_contrato', models.CharField(choices=[('Beca', 'Beca'), ('Profesional', 'Profesional'), ('Amateur', 'Amateur'), ('Prueba', 'Prueba')], max_length=30)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('moneda', models.CharField(default='USD', max_length=5)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='stats.jugador')),
            ],
            options={
                'db_table': 'contratos_internos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AntecedentesSalud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('medicamentos_regulares', models.TextField(blank=True, null=True)),
                ('condiciones_cronicas', models.TextField(blank=True, null=True)),
                ('contacto_medico_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('contacto_medico_tel', models.CharField(blank=True, max_length=20, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_salud', to='stats.jugador')),
            ],
            options={
                'db_table': 'antecedentes_salud',
            },
        ),
        migrations.CreateModel(
            name='LesionRegistro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('zona_cuerpo', models.CharField(max_length=80)),
                ('tipo_lesion', models.CharField(blank=True, max_length=50, null=True)),
                ('gravedad', models.CharField(blank=True, choices=[('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave')], max_length=20, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('medico_tratante', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesiones', to='stats.jugador')),
            ],
            options={
                'db_table': 'lesiones_registro',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rival', models.CharField(max_length=150)),
                ('es_local', models.BooleanField(default=True)),
                ('fecha', models.DateTimeField()),
                ('tipo_partido', models.CharField(choices=[('Liga', 'Liga'), ('Copa', 'Copa'), ('Amistoso', 'Amistoso'), ('Torneo', 'Torneo'), ('Playoffs', 'Playoffs')], default='Liga', max_length=30)),
                ('goles_favor', models.SmallIntegerField(default=0)),
                ('goles_contra', models.SmallIntegerField(default=0)),
                ('resultado_final', models.CharField(blank=True, max_length=10, null=True)),
                ('estado_partido', models.CharField(choices=[('Programado', 'Programado'), ('En curso', 'En curso'), ('Finalizado', 'Finalizado'), ('Suspendido', 'Suspendido'), ('Aplazado', 'Aplazado')], default='Programado', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(db_column='categoria_id', on_delete=django.db.models.deletion.CASCADE, related_name='partidos', to='stats.categoria')),
            ],
            options={
                'db_table': 'partidos',
            },
        ),
        migrations.CreateModel(
            name='PlanAlimenticio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion_dieta', models.TextField(blank=True, null=True)),
                ('calorias_totales', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('proteina_gr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('carbohidratos_gr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grasas_gr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hidratacion_ml', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('nutricionista', models.CharField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_alimenticios', to='stats.jugador')),
            ],
            options={
                'db_table': 'planes_alimenticios',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='JugadorPosicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_principal', models.BooleanField(default=False)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones_asignadas', to='stats.jugador')),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores_asignados', to='stats.posicion')),
            ],
            options={
                'verbose_name': 'Posición de Jugador',
                'verbose_name_plural': 'Posiciones de Jugadores',
                'db_table': 'jugadores_posiciones',
            },
        ),
        migrations.AddField(
            model_name='jugador',
            name='posiciones',
            field=models.ManyToManyField(related_name='jugadores', through='stats.JugadorPosicion', to='stats.posicion'),
        ),
        migrations.CreateModel(
            name='Alineacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('es_titular', models.BooleanField(default=True)),
                ('minuto_entrada', models.SmallIntegerField(default=0)),
                ('minuto_salida', models.SmallIntegerField(default=90)),
                ('minutos_jugados', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.functions.comparison.Least(models.F('minuto_salida'), 90), '-', django.db.models.functions.comparison.Greatest(models.F('minuto_entrada'), 0)), output_field=models.SmallIntegerField())),
                ('jugador', models.ForeignKey(db_column='jugador_id', on_delete=django.db.models.deletion.CASCADE, related_name='alineaciones', to='stats.jugador')),
                ('partido', models.ForeignKey(db_column='partido_id', on_delete=django.db.models.deletion.CASCADE, related_name='alineaciones', to='stats.partido')),
                ('posicion_partido', models.ForeignKey(blank=True, db_column='posicion_partido_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alineaciones', to='stats.posicion')),
            ],
            options={
                'db_table': 'alineaciones',
            },
        ),
        migrations.CreateModel(
            name='ProspectoSeguimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_jugador', models.CharField(blank=True, max_length=150, null=True)),
                ('equipo_actual', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=80, null=True)),
                ('estado', models.CharField(choices=[('Seguimiento', 'Seguimiento'), ('Contactado', 'Contactado'), ('En evaluación', 'En evaluación'), ('Oferta enviada', 'Oferta enviada'), ('Reclutado', 'Reclutado'), ('Descartado', 'Descartado')], default='Seguimiento', max_length=30)),
                ('fecha_primer_contacto', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospectos', to='stats.jugador')),
                ('posicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.posicion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospectos_seguidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prospectos_seguimiento',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ReporteScouting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valoracion_estrellas', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario_tecnico', models.TextField(blank=True, null=True)),
                ('partido_observado', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_reporte', models.DateField(default=datetime.date.today)),
                ('jugador', models.ForeignKey(blank=True, db_column='jugador_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes_scouting', to='stats.jugador')),
                ('prospecto', models.ForeignKey(blank=True, db_column='prospecto_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes_scouting', to='stats.prospectoseguimiento')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='reportes_scouting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reportes_scouting',
            },
        ),
        migrations.CreateModel(
            name='MetricaTecnica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('control', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('pase_corto', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('pase_largo', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('tiro', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('regate', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('cabeceo', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('velocidad', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('resistencia', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('puntaje_tecnico', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.functions.comparison.Coalesce(models.F('control'), 0), '+', django.db.models.functions.comparison.Coalesce(models.F('pase_corto'), 0)), '+', django.db.models.functions.comparison.Coalesce(models.F('pase_largo'), 0)), '+', django.db.models.functions.comparison.Coalesce(models.F('tiro'), 0)), '+', django.db.models.functions.comparison.Coalesce(models.F('regate'), 0)), '+', django.db.models.functions.comparison.Coalesce(models.F('cabeceo'), 0)), '+', django.db.models.functions.comparison.Coalesce(models.F('velocidad'), 0)), '+', django.db.models.functions.comparison.Coalesce(models.F('resistencia'), 0)), '/', models.Value(8.0)), output_field=models.DecimalField(decimal_places=2, max_digits=5))),
                ('reporte', models.OneToOneField(db_column='reporte_id', on_delete=django.db.models.deletion.CASCADE, related_name='metricas_tecnicas', to='stats.reportescouting')),
            ],
            options={
                'db_table': 'metricas_tecnicas',
            },
        ),
        migrations.CreateModel(
            name='MetricaTactica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ubicacion', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('lectura_juego', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('sacrificio', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('liderazgo', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('presion', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('trabajo_equipo', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('puntaje_tactico', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.functions.comparison.Coalesce(models.F('ubicacion'), 0), '+', django.db.models.functions.comparison.Coalesce(models.F('lectura_juego'), 0)), '+', django.db.models.functions.comparison.Coalesce(models.F('sacrificio'), 0)), '+', django.db.models.functions.comparison.Coalesce(models.F('liderazgo'), 0)), '+', django.db.models.functions.comparison.Coalesce(models.F('presion'), 0)), '+', django.db.models.functions.comparison.Coalesce(models.F('trabajo_equipo'), 0)), '/', models.Value(6.0)), output_field=models.DecimalField(decimal_places=2, max_digits=5))),
                ('reporte', models.OneToOneField(db_column='reporte_id', on_delete=django.db.models.deletion.CASCADE, related_name='metricas_tacticas', to='stats.reportescouting')),
            ],
            options={
                'db_table': 'metricas_tacticas',
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('es_contacto_emergencia', models.BooleanField(default=False)),
                ('es_agente', models.BooleanField(default=False)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representantes', to='stats.jugador')),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
                'db_table': 'representantes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_sede', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('tipo_superficie', models.CharField(blank=True, max_length=50, null=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='stats.entidad')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'db_table': 'sedes',
                'ordering': ['nombre_sede'],
            },
        ),
        migrations.AddField(
            model_name='partido',
            name='sede',
            field=models.ForeignKey(blank=True, db_column='sede_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos', to='stats.sede'),
        ),
        migrations.CreateModel(
            name='SesionRehabilitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ejercicios_realizados', models.TextField()),
                ('duracion_minutos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dolor_nivel', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_sesion', models.DateField(default=django.utils.timezone.now)),
                ('fisioterapeuta', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('lesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='stats.lesionregistro')),
            ],
            options={
                'db_table': 'sesiones_rehabilitacion',
                'ordering': ['-fecha_sesion'],
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('Basico', 'Basico'), ('Premium', 'Premium')], max_length=20)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Cancelado', 'Cancelado'), ('Vencido', 'Vencido'), ('Suspendido', 'Suspendido')], default='Activo', max_length=20)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripcion',
                'verbose_name_plural': 'Suscripciones',
                'db_table': 'suscripciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='TestRendimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('velocidad_30m_seg', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('velocidad_60m_seg', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('salto_vertical_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('salto_horizontal_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('resistencia_vo2max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resistencia_nivel', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('flexibilidad_cm', models.SmallIntegerField(blank=True, null=True)),
                ('agilidad_seg', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('fecha_test', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_rendimiento', to='stats.jugador')),
            ],
            options={
                'db_table': 'tests_rendimiento',
                'ordering': ['-fecha_test'],
            },
        ),
        migrations.CreateModel(
            name='ValoracionEconomica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moneda', models.CharField(default='USD', max_length=5)),
                ('fecha_valoracion', models.DateField(default=datetime.date.today)),
                ('metodo_valoracion', models.CharField(blank=True, max_length=80, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('jugador', models.ForeignKey(db_column='jugador_id', on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_economicas', to='stats.jugador')),
            ],
            options={
                'db_table': 'valoracion_economica',
            },
        ),
        migrations.CreateModel(
            name='EventoLive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('minuto', models.SmallIntegerField()),
                ('tipo_evento', models.CharField(choices=[('Gol', 'Gol'), ('Autogol', 'Autogol'), ('Asistencia', 'Asistencia'), ('Tarjeta amarilla', 'Tarjeta amarilla'), ('Tarjeta roja', 'Tarjeta roja'), ('Doble amarilla', 'Doble amarilla'), ('Penalti anotado', 'Penalti anotado'), ('Penalti fallado', 'Penalti fallado'), ('Cambio entrada', 'Cambio entrada'), ('Cambio salida', 'Cambio salida'), ('Lesion', 'Lesion')], max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(db_column='jugador_id', on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='stats.jugador')),
                ('jugador_secundario', models.ForeignKey(blank=True, db_column='jugador_secundario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_asistidos', to='stats.jugador')),
                ('partido', models.ForeignKey(db_column='partido_id', on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='stats.partido')),
            ],
            options={
                'db_table': 'eventos_live',
                'constraints': [models.CheckConstraint(condition=models.Q(('tipo_evento__in', ['Gol', 'Autogol', 'Asistencia', 'Tarjeta amarilla', 'Tarjeta roja', 'Doble amarilla', 'Penalti anotado', 'Penalti fallado', 'Cambio entrada', 'Cambio salida', 'Lesion'])), name='chk_eventos_live_tipo_evento')],
            },
        ),
        migrations.CreateModel(
            name='EvaluacionPostPartido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('calificacion', models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)])),
                ('puntos_positivos', models.TextField(blank=True, null=True)),
                ('puntos_a_mejorar', models.TextField(blank=True, null=True)),
                ('es_visible_jugador', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(db_column='jugador_id', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_post_partido', to='stats.jugador')),
                ('partido', models.ForeignKey(db_column='partido_id', on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones_post_partido', to='stats.partido')),
            ],
            options={
                'db_table': 'evaluacion_post_partido',
                'constraints': [models.UniqueConstraint(fields=('partido', 'jugador'), name='unique_partido_jugador_evaluacion'), models.CheckConstraint(condition=models.Q(('calificacion__gte', 1.0), ('calificacion__lte', 10.0)), name='chk_evaluacion_calificacion_range')],
            },
        ),
        migrations.AddConstraint(
            model_name='jugadorposicion',
            constraint=models.UniqueConstraint(fields=('jugador', 'posicion'), name='unique_jugador_posicion'),
        ),
        migrations.AddConstraint(
            model_name='alineacion',
            constraint=models.UniqueConstraint(fields=('partido', 'jugador'), name='unique_partido_jugador_alineacion'),
        ),
        migrations.AddConstraint(
            model_name='reportescouting',
            constraint=models.CheckConstraint(condition=models.Q(('jugador__isnull', False), ('prospecto__isnull', False), _connector='OR'), name='chk_sujeto_reporte'),
        ),
        migrations.AddConstraint(
            model_name='reportescouting',
            constraint=models.CheckConstraint(condition=models.Q(('valoracion_estrellas__gte', 1), ('valoracion_estrellas__lte', 5)), name='chk_valoracion_estrellas_range'),
        ),
        migrations.AddConstraint(
            model_name='metricatecnica',
            constraint=models.CheckConstraint(condition=models.Q(('control__isnull', True), models.Q(('control__gte', 1), ('control__lte', 100)), _connector='OR'), name='chk_metricas_tecnicas_control'),
        ),
        migrations.AddConstraint(
            model_name='metricatecnica',
            constraint=models.CheckConstraint(condition=models.Q(('pase_corto__isnull', True), models.Q(('pase_corto__gte', 1), ('pase_corto__lte', 100)), _connector='OR'), name='chk_metricas_tecnicas_pase_corto'),
        ),
        migrations.AddConstraint(
            model_name='metricatecnica',
            constraint=models.CheckConstraint(condition=models.Q(('pase_largo__isnull', True), models.Q(('pase_largo__gte', 1), ('pase_largo__lte', 100)), _connector='OR'), name='chk_metricas_tecnicas_pase_largo'),
        ),
        migrations.AddConstraint(
            model_name='metricatecnica',
            constraint=models.CheckConstraint(condition=models.Q(('tiro__isnull', True), models.Q(('tiro__gte', 1), ('tiro__lte', 100)), _connector='OR'), name='chk_metricas_tecnicas_tiro'),
        ),
        migrations.AddConstraint(
            model_name='metricatecnica',
            constraint=models.CheckConstraint(condition=models.Q(('regate__isnull', True), models.Q(('regate__gte', 1), ('regate__lte', 100)), _connector='OR'), name='chk_metricas_tecnicas_regate'),
        ),
        migrations.AddConstraint(
            model_name='metricatecnica',
            constraint=models.CheckConstraint(condition=models.Q(('cabeceo__isnull', True), models.Q(('cabeceo__gte', 1), ('cabeceo__lte', 100)), _connector='OR'), name='chk_metricas_tecnicas_cabeceo'),
        ),
        migrations.AddConstraint(
            model_name='metricatecnica',
            constraint=models.CheckConstraint(condition=models.Q(('velocidad__isnull', True), models.Q(('velocidad__gte', 1), ('velocidad__lte', 100)), _connector='OR'), name='chk_metricas_tecnicas_velocidad'),
        ),
        migrations.AddConstraint(
            model_name='metricatecnica',
            constraint=models.CheckConstraint(condition=models.Q(('resistencia__isnull', True), models.Q(('resistencia__gte', 1), ('resistencia__lte', 100)), _connector='OR'), name='chk_metricas_tecnicas_resistencia'),
        ),
        migrations.AddConstraint(
            model_name='metricatactica',
            constraint=models.CheckConstraint(condition=models.Q(('ubicacion__isnull', True), models.Q(('ubicacion__gte', 1), ('ubicacion__lte', 100)), _connector='OR'), name='chk_metricas_tacticas_ubicacion'),
        ),
        migrations.AddConstraint(
            model_name='metricatactica',
            constraint=models.CheckConstraint(condition=models.Q(('lectura_juego__isnull', True), models.Q(('lectura_juego__gte', 1), ('lectura_juego__lte', 100)), _connector='OR'), name='chk_metricas_tacticas_lectura_juego'),
        ),
        migrations.AddConstraint(
            model_name='metricatactica',
            constraint=models.CheckConstraint(condition=models.Q(('sacrificio__isnull', True), models.Q(('sacrificio__gte', 1), ('sacrificio__lte', 100)), _connector='OR'), name='chk_metricas_tacticas_sacrificio'),
        ),
        migrations.AddConstraint(
            model_name='metricatactica',
            constraint=models.CheckConstraint(condition=models.Q(('liderazgo__isnull', True), models.Q(('liderazgo__gte', 1), ('liderazgo__lte', 100)), _connector='OR'), name='chk_metricas_tacticas_liderazgo'),
        ),
        migrations.AddConstraint(
            model_name='metricatactica',
            constraint=models.CheckConstraint(condition=models.Q(('presion__isnull', True), models.Q(('presion__gte', 1), ('presion__lte', 100)), _connector='OR'), name='chk_metricas_tacticas_presion'),
        ),
        migrations.AddConstraint(
            model_name='metricatactica',
            constraint=models.CheckConstraint(condition=models.Q(('trabajo_equipo__isnull', True), models.Q(('trabajo_equipo__gte', 1), ('trabajo_equipo__lte', 100)), _connector='OR'), name='chk_metricas_tacticas_trabajo_equipo'),
        ),
        migrations.AddConstraint(
            model_name='partido',
            constraint=models.CheckConstraint(condition=models.Q(('tipo_partido__in', ['Liga', 'Copa', 'Amistoso', 'Torneo', 'Playoffs'])), name='chk_partidos_tipo_partido'),
        ),
        migrations.AddConstraint(
            model_name='partido',
            constraint=models.CheckConstraint(condition=models.Q(('estado_partido__in', ['Programado', 'En curso', 'Finalizado', 'Suspendido', 'Aplazado'])), name='chk_partidos_estado_partido'),
        ),
    ]
