# Generated by Django 6.0.6 on 2026-07-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='es_local',
        ),
        migrations.RemoveField(
            model_name='partido',
            name='rival',
        ),
        migrations.AddField(
            model_name='partido',
            name='equipo_local',
            field=models.CharField(default='Local', max_length=150),
        ),
        migrations.AddField(
            model_name='partido',
            name='equipo_visitante',
            field=models.CharField(default='Visitante', max_length=150),
        ),
    ]
