# Generated by Django 6.0.6 on 2026-06-23 02:12


## SANTIAGO COLIMBA

import datetime
import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.comparison
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stats", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "categorias",
            },
        ),
        migrations.CreateModel(
            name="Jugador",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "jugadores",
            },
        ),
        migrations.CreateModel(
            name="Posicion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "posiciones",
            },
        ),
        migrations.CreateModel(
            name="ProspectoSeguimiento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "prospectos_seguimiento",
            },
        ),
        migrations.CreateModel(
            name="Sede",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nombre", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "db_table": "sedes",
            },
        ),
        migrations.CreateModel(
            name="Partido",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("rival", models.CharField(max_length=150)),
                ("es_local", models.BooleanField(default=True)),
                ("fecha", models.DateTimeField()),
                (
                    "tipo_partido",
                    models.CharField(
                        choices=[
                            ("Liga", "Liga"),
                            ("Copa", "Copa"),
                            ("Amistoso", "Amistoso"),
                            ("Torneo", "Torneo"),
                            ("Playoffs", "Playoffs"),
                        ],
                        default="Liga",
                        max_length=30,
                    ),
                ),
                ("goles_favor", models.SmallIntegerField(default=0)),
                ("goles_contra", models.SmallIntegerField(default=0)),
                (
                    "resultado_final",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "estado_partido",
                    models.CharField(
                        choices=[
                            ("Programado", "Programado"),
                            ("En curso", "En curso"),
                            ("Finalizado", "Finalizado"),
                            ("Suspendido", "Suspendido"),
                            ("Aplazado", "Aplazado"),
                        ],
                        default="Programado",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        db_column="categoria_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidos",
                        to="stats.categoria",
                    ),
                ),
                (
                    "sede",
                    models.ForeignKey(
                        blank=True,
                        db_column="sede_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="partidos",
                        to="stats.sede",
                    ),
                ),
            ],
            options={
                "db_table": "partidos",
            },
        ),
        migrations.CreateModel(
            name="ReporteScouting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "valoracion_estrellas",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comentario_tecnico", models.TextField(blank=True, null=True)),
                (
                    "partido_observado",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("fecha_reporte", models.DateField(default=datetime.date.today)),
                (
                    "jugador",
                    models.ForeignKey(
                        blank=True,
                        db_column="jugador_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_scouting",
                        to="stats.jugador",
                    ),
                ),
                (
                    "prospecto",
                    models.ForeignKey(
                        blank=True,
                        db_column="prospecto_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_scouting",
                        to="stats.prospectoseguimiento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_scouting",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reportes_scouting",
            },
        ),
        migrations.CreateModel(
            name="MetricaTecnica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "control",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "pase_corto",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "pase_largo",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "tiro",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "regate",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "cabeceo",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "velocidad",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "resistencia",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "puntaje_tecnico",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        django.db.models.expressions.CombinedExpression(
                                            django.db.models.expressions.CombinedExpression(
                                                django.db.models.expressions.CombinedExpression(
                                                    django.db.models.expressions.CombinedExpression(
                                                        django.db.models.functions.comparison.Coalesce(
                                                            models.F("control"), 0
                                                        ),
                                                        "+",
                                                        django.db.models.functions.comparison.Coalesce(
                                                            models.F("pase_corto"), 0
                                                        ),
                                                    ),
                                                    "+",
                                                    django.db.models.functions.comparison.Coalesce(
                                                        models.F("pase_largo"), 0
                                                    ),
                                                ),
                                                "+",
                                                django.db.models.functions.comparison.Coalesce(
                                                    models.F("tiro"), 0
                                                ),
                                            ),
                                            "+",
                                            django.db.models.functions.comparison.Coalesce(
                                                models.F("regate"), 0
                                            ),
                                        ),
                                        "+",
                                        django.db.models.functions.comparison.Coalesce(
                                            models.F("cabeceo"), 0
                                        ),
                                    ),
                                    "+",
                                    django.db.models.functions.comparison.Coalesce(
                                        models.F("velocidad"), 0
                                    ),
                                ),
                                "+",
                                django.db.models.functions.comparison.Coalesce(
                                    models.F("resistencia"), 0
                                ),
                            ),
                            "/",
                            models.Value(8.0),
                        ),
                        output_field=models.DecimalField(
                            decimal_places=2, max_digits=5
                        ),
                    ),
                ),
                (
                    "reporte",
                    models.OneToOneField(
                        db_column="reporte_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metricas_tecnicas",
                        to="stats.reportescouting",
                    ),
                ),
            ],
            options={
                "db_table": "metricas_tecnicas",
            },
        ),
        migrations.CreateModel(
            name="MetricaTactica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ubicacion",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "lectura_juego",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "sacrificio",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "liderazgo",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "presion",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "trabajo_equipo",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "puntaje_tactico",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        django.db.models.expressions.CombinedExpression(
                                            django.db.models.expressions.CombinedExpression(
                                                django.db.models.functions.comparison.Coalesce(
                                                    models.F("ubicacion"), 0
                                                ),
                                                "+",
                                                django.db.models.functions.comparison.Coalesce(
                                                    models.F("lectura_juego"), 0
                                                ),
                                            ),
                                            "+",
                                            django.db.models.functions.comparison.Coalesce(
                                                models.F("sacrificio"), 0
                                            ),
                                        ),
                                        "+",
                                        django.db.models.functions.comparison.Coalesce(
                                            models.F("liderazgo"), 0
                                        ),
                                    ),
                                    "+",
                                    django.db.models.functions.comparison.Coalesce(
                                        models.F("presion"), 0
                                    ),
                                ),
                                "+",
                                django.db.models.functions.comparison.Coalesce(
                                    models.F("trabajo_equipo"), 0
                                ),
                            ),
                            "/",
                            models.Value(6.0),
                        ),
                        output_field=models.DecimalField(
                            decimal_places=2, max_digits=5
                        ),
                    ),
                ),
                (
                    "reporte",
                    models.OneToOneField(
                        db_column="reporte_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metricas_tacticas",
                        to="stats.reportescouting",
                    ),
                ),
            ],
            options={
                "db_table": "metricas_tacticas",
            },
        ),
        migrations.CreateModel(
            name="ValoracionEconomica",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "valor_estimado",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("moneda", models.CharField(default="USD", max_length=5)),
                ("fecha_valoracion", models.DateField(default=datetime.date.today)),
                (
                    "metodo_valoracion",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "jugador",
                    models.ForeignKey(
                        db_column="jugador_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoraciones_economicas",
                        to="stats.jugador",
                    ),
                ),
            ],
            options={
                "db_table": "valoracion_economica",
            },
        ),
        migrations.CreateModel(
            name="EventoLive",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("minuto", models.SmallIntegerField()),
                (
                    "tipo_evento",
                    models.CharField(
                        choices=[
                            ("Gol", "Gol"),
                            ("Autogol", "Autogol"),
                            ("Asistencia", "Asistencia"),
                            ("Tarjeta amarilla", "Tarjeta amarilla"),
                            ("Tarjeta roja", "Tarjeta roja"),
                            ("Doble amarilla", "Doble amarilla"),
                            ("Penalti anotado", "Penalti anotado"),
                            ("Penalti fallado", "Penalti fallado"),
                            ("Cambio entrada", "Cambio entrada"),
                            ("Cambio salida", "Cambio salida"),
                            ("Lesion", "Lesion"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "jugador",
                    models.ForeignKey(
                        db_column="jugador_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="stats.jugador",
                    ),
                ),
                (
                    "jugador_secundario",
                    models.ForeignKey(
                        blank=True,
                        db_column="jugador_secundario_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_asistidos",
                        to="stats.jugador",
                    ),
                ),
                (
                    "partido",
                    models.ForeignKey(
                        db_column="partido_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="stats.partido",
                    ),
                ),
            ],
            options={
                "db_table": "eventos_live",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "tipo_evento__in",
                                [
                                    "Gol",
                                    "Autogol",
                                    "Asistencia",
                                    "Tarjeta amarilla",
                                    "Tarjeta roja",
                                    "Doble amarilla",
                                    "Penalti anotado",
                                    "Penalti fallado",
                                    "Cambio entrada",
                                    "Cambio salida",
                                    "Lesion",
                                ],
                            )
                        ),
                        name="chk_eventos_live_tipo_evento",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EvaluacionPostPartido",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "calificacion",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                ("puntos_positivos", models.TextField(blank=True, null=True)),
                ("puntos_a_mejorar", models.TextField(blank=True, null=True)),
                ("es_visible_jugador", models.BooleanField(default=False)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "jugador",
                    models.ForeignKey(
                        db_column="jugador_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones_post_partido",
                        to="stats.jugador",
                    ),
                ),
                (
                    "partido",
                    models.ForeignKey(
                        db_column="partido_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones_post_partido",
                        to="stats.partido",
                    ),
                ),
            ],
            options={
                "db_table": "evaluacion_post_partido",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("partido", "jugador"),
                        name="unique_partido_jugador_evaluacion",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("calificacion__gte", 1.0), ("calificacion__lte", 10.0)
                        ),
                        name="chk_evaluacion_calificacion_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Alineacion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("es_titular", models.BooleanField(default=True)),
                ("minuto_entrada", models.SmallIntegerField(default=0)),
                ("minuto_salida", models.SmallIntegerField(default=90)),
                (
                    "minutos_jugados",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            django.db.models.functions.comparison.Least(
                                models.F("minuto_salida"), 90
                            ),
                            "-",
                            django.db.models.functions.comparison.Greatest(
                                models.F("minuto_entrada"), 0
                            ),
                        ),
                        output_field=models.SmallIntegerField(),
                    ),
                ),
                (
                    "jugador",
                    models.ForeignKey(
                        db_column="jugador_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alineaciones",
                        to="stats.jugador",
                    ),
                ),
                (
                    "partido",
                    models.ForeignKey(
                        db_column="partido_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alineaciones",
                        to="stats.partido",
                    ),
                ),
                (
                    "posicion_partido",
                    models.ForeignKey(
                        blank=True,
                        db_column="posicion_partido_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alineaciones",
                        to="stats.posicion",
                    ),
                ),
            ],
            options={
                "db_table": "alineaciones",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("partido", "jugador"),
                        name="unique_partido_jugador_alineacion",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="reportescouting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("jugador__isnull", False),
                    ("prospecto__isnull", False),
                    _connector="OR",
                ),
                name="chk_sujeto_reporte",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportescouting",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valoracion_estrellas__gte", 1), ("valoracion_estrellas__lte", 5)
                ),
                name="chk_valoracion_estrellas_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="metricatecnica",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("control__isnull", True),
                    models.Q(("control__gte", 1), ("control__lte", 100)),
                    _connector="OR",
                ),
                name="chk_metricas_tecnicas_control",
            ),
        ),
        migrations.AddConstraint(
            model_name="metricatecnica",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pase_corto__isnull", True),
                    models.Q(("pase_corto__gte", 1), ("pase_corto__lte", 100)),
                    _connector="OR",
                ),
                name="chk_metricas_tecnicas_pase_corto",
            ),
        ),
        migrations.AddConstraint(
            model_name="metricatecnica",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pase_largo__isnull", True),
                    models.Q(("pase_largo__gte", 1), ("pase_largo__lte", 100)),
                    _connector="OR",
                ),
                name="chk_metricas_tecnicas_pase_largo",
            ),
        ),
        migrations.AddConstraint(
            model_name="metricatecnica",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tiro__isnull", True),
                    models.Q(("tiro__gte", 1), ("tiro__lte", 100)),
                    _connector="OR",
                ),
                name="chk_metricas_tecnicas_tiro",
            ),
        ),
        migrations.AddConstraint(
            model_name="metricatecnica",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("regate__isnull", True),
                    models.Q(("regate__gte", 1), ("regate__lte", 100)),
                    _connector="OR",
                ),
                name="chk_metricas_tecnicas_regate",
            ),
        ),
        migrations.AddConstraint(
            model_name="metricatecnica",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("cabeceo__isnull", True),
                    models.Q(("cabeceo__gte", 1), ("cabeceo__lte", 100)),
                    _connector="OR",
                ),
                name="chk_metricas_tecnicas_cabeceo",
            ),
        ),
        migrations.AddConstraint(
            model_name="metricatecnica",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("velocidad__isnull", True),
                    models.Q(("velocidad__gte", 1), ("velocidad__lte", 100)),
                    _connector="OR",
                ),
                name="chk_metricas_tecnicas_velocidad",
            ),
        ),
        migrations.AddConstraint(
            model_name="metricatecnica",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("resistencia__isnull", True),
                    models.Q(("resistencia__gte", 1), ("resistencia__lte", 100)),
                    _connector="OR",
                ),
                name="chk_metricas_tecnicas_resistencia",
            ),
        ),
        migrations.AddConstraint(
            model_name="metricatactica",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ubicacion__isnull", True),
                    models.Q(("ubicacion__gte", 1), ("ubicacion__lte", 100)),
                    _connector="OR",
                ),
                name="chk_metricas_tacticas_ubicacion",
            ),
        ),
        migrations.AddConstraint(
            model_name="metricatactica",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lectura_juego__isnull", True),
                    models.Q(("lectura_juego__gte", 1), ("lectura_juego__lte", 100)),
                    _connector="OR",
                ),
                name="chk_metricas_tacticas_lectura_juego",
            ),
        ),
        migrations.AddConstraint(
            model_name="metricatactica",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sacrificio__isnull", True),
                    models.Q(("sacrificio__gte", 1), ("sacrificio__lte", 100)),
                    _connector="OR",
                ),
                name="chk_metricas_tacticas_sacrificio",
            ),
        ),
        migrations.AddConstraint(
            model_name="metricatactica",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("liderazgo__isnull", True),
                    models.Q(("liderazgo__gte", 1), ("liderazgo__lte", 100)),
                    _connector="OR",
                ),
                name="chk_metricas_tacticas_liderazgo",
            ),
        ),
        migrations.AddConstraint(
            model_name="metricatactica",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("presion__isnull", True),
                    models.Q(("presion__gte", 1), ("presion__lte", 100)),
                    _connector="OR",
                ),
                name="chk_metricas_tacticas_presion",
            ),
        ),
        migrations.AddConstraint(
            model_name="metricatactica",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("trabajo_equipo__isnull", True),
                    models.Q(("trabajo_equipo__gte", 1), ("trabajo_equipo__lte", 100)),
                    _connector="OR",
                ),
                name="chk_metricas_tacticas_trabajo_equipo",
            ),
        ),
        migrations.AddConstraint(
            model_name="partido",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "tipo_partido__in",
                        ["Liga", "Copa", "Amistoso", "Torneo", "Playoffs"],
                    )
                ),
                name="chk_partidos_tipo_partido",
            ),
        ),
        migrations.AddConstraint(
            model_name="partido",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "estado_partido__in",
                        [
                            "Programado",
                            "En curso",
                            "Finalizado",
                            "Suspendido",
                            "Aplazado",
                        ],
                    )
                ),
                name="chk_partidos_estado_partido",
            ),
        ),
    ]
