# Generated by Django 6.0.6 on 2026-06-23 02:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='Activo', max_length=20)),
            ],
            options={
                'db_table': 'jugadores',
            },
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_posicion', models.CharField(max_length=80, unique=True)),
                ('zona', models.CharField(default='Mediocampo', max_length=20)),
            ],
            options={
                'db_table': 'posiciones',
            },
        ),
        migrations.CreateModel(
            name='HistorialAntropometrico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grasa_corporal', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('masa_muscular', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fecha_toma', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_antropometrico', to='stats.jugador')),
            ],
            options={
                'db_table': 'historial_antropometrico',
                'ordering': ['-fecha_toma'],
            },
        ),
        migrations.CreateModel(
            name='ContratoInterno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_contrato', models.CharField(choices=[('Beca', 'Beca'), ('Profesional', 'Profesional'), ('Amateur', 'Amateur'), ('Prueba', 'Prueba')], max_length=30)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('moneda', models.CharField(default='USD', max_length=5)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='stats.jugador')),
            ],
            options={
                'db_table': 'contratos_internos',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AntecedentesSalud',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('medicamentos_regulares', models.TextField(blank=True, null=True)),
                ('condiciones_cronicas', models.TextField(blank=True, null=True)),
                ('contacto_medico_nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('contacto_medico_tel', models.CharField(blank=True, max_length=20, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_salud', to='stats.jugador')),
            ],
            options={
                'db_table': 'antecedentes_salud',
            },
        ),
        migrations.CreateModel(
            name='LesionRegistro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('zona_cuerpo', models.CharField(max_length=80)),
                ('tipo_lesion', models.CharField(blank=True, max_length=50, null=True)),
                ('gravedad', models.CharField(blank=True, choices=[('Leve', 'Leve'), ('Moderada', 'Moderada'), ('Grave', 'Grave')], max_length=20, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('medico_tratante', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesiones', to='stats.jugador')),
            ],
            options={
                'db_table': 'lesiones_registro',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='PlanAlimenticio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion_dieta', models.TextField(blank=True, null=True)),
                ('calorias_totales', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('proteina_gr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('carbohidratos_gr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('grasas_gr', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hidratacion_ml', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('nutricionista', models.CharField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_alimenticios', to='stats.jugador')),
            ],
            options={
                'db_table': 'planes_alimenticios',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ProspectoSeguimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_jugador', models.CharField(blank=True, max_length=150, null=True)),
                ('equipo_actual', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=80, null=True)),
                ('estado', models.CharField(choices=[('Seguimiento', 'Seguimiento'), ('Contactado', 'Contactado'), ('En evaluación', 'En evaluación'), ('Oferta enviada', 'Oferta enviada'), ('Reclutado', 'Reclutado'), ('Descartado', 'Descartado')], default='Seguimiento', max_length=30)),
                ('fecha_primer_contacto', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospectos', to='stats.jugador')),
                ('posicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.posicion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prospectos_seguidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prospectos_seguimiento',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='SesionRehabilitacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ejercicios_realizados', models.TextField()),
                ('duracion_minutos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dolor_nivel', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fecha_sesion', models.DateField(default=django.utils.timezone.now)),
                ('fisioterapeuta', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('lesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='stats.lesionregistro')),
            ],
            options={
                'db_table': 'sesiones_rehabilitacion',
                'ordering': ['-fecha_sesion'],
            },
        ),
        migrations.CreateModel(
            name='TestRendimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('velocidad_30m_seg', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('velocidad_60m_seg', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('salto_vertical_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('salto_horizontal_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('resistencia_vo2max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resistencia_nivel', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('flexibilidad_cm', models.SmallIntegerField(blank=True, null=True)),
                ('agilidad_seg', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('fecha_test', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests_rendimiento', to='stats.jugador')),
            ],
            options={
                'db_table': 'tests_rendimiento',
                'ordering': ['-fecha_test'],
            },
        ),
    ]
