# Generated by Django 6.0.6 on 2026-07-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_remove_partido_es_local_remove_partido_rival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='anio_fundacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entidad',
            name='director_tecnico',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
