# Generated by Django 6.0.6 on 2026-06-24 03:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_suscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_entidad', models.CharField(max_length=150)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(default='Ecuador', max_length=100)),
                ('telefono_contacto', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'db_table': 'entidades',
                'ordering': ['nombre_entidad'],
            },
        ),
    ]
