# Generated by Django 6.0.6 on 2026-06-24 04:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_entidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_sede', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, max_length=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, max_length=9, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
                ('tipo_superficie', models.CharField(blank=True, max_length=50, null=True)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='stats.entidad')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'db_table': 'sedes',
                'ordering': ['nombre_sede'],
            },
        ),
    ]
