# Generated by Django 6.0.6 on 2026-07-19 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_entidad_anio_fundacion_entidad_director_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('Coach', 'Coach'), ('Scout', 'Scout'), ('Player', 'Player'), ('Admin', 'Admin')], max_length=20),
        ),
    ]
