# Generated by Django 6.0.6 on 2026-06-24 04:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_posicion', models.CharField(max_length=80, unique=True)),
                ('abreviatura', models.CharField(blank=True, max_length=10, null=True)),
                ('zona', models.CharField(choices=[('Porteria', 'Porteria'), ('Defensa', 'Defensa'), ('Mediocampo', 'Mediocampo'), ('Ataque', 'Ataque')], max_length=20)),
            ],
            options={
                'verbose_name': 'Posición',
                'verbose_name_plural': 'Posiciones',
                'db_table': 'posiciones',
                'ordering': ['zona', 'nombre_posicion'],
            },
        ),
    ]
