# Generated by Django 6.0.6 on 2026-06-24 04:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_posicion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('foto_url', models.URLField(blank=True, max_length=500, null=True)),
                ('numero_camiseta', models.SmallIntegerField(blank=True, null=True)),
                ('pie_dominante', models.CharField(choices=[('Derecho', 'Derecho'), ('Izquierdo', 'Izquierdo'), ('Ambidiestro', 'Ambidiestro')], default='Derecho', max_length=15)),
                ('nacionalidad', models.CharField(blank=True, max_length=80, null=True)),
                ('documento_identidad', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Lesionado', 'Lesionado'), ('Suspendido', 'Suspendido'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='stats.categoria')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='stats.entidad')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'jugadores',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
    ]
