# Generated by Django 6.0.6 on 2026-06-24 04:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_jugador'),
    ]

    operations = [
        migrations.CreateModel(
            name='JugadorPosicion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('es_principal', models.BooleanField(default=False)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones_asignadas', to='stats.jugador')),
                ('posicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores_asignados', to='stats.posicion')),
            ],
            options={
                'verbose_name': 'Posición de Jugador',
                'verbose_name_plural': 'Posiciones de Jugadores',
                'db_table': 'jugadores_posiciones',
            },
        ),
        migrations.AddField(
            model_name='jugador',
            name='posiciones',
            field=models.ManyToManyField(related_name='jugadores', through='stats.JugadorPosicion', to='stats.posicion'),
        ),
        migrations.AddConstraint(
            model_name='jugadorposicion',
            constraint=models.UniqueConstraint(fields=('jugador', 'posicion'), name='unique_jugador_posicion'),
        ),
    ]
