# Generated by Django 6.0.6 on 2026-06-24 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_jugadorposicion_jugador_posiciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('es_contacto_emergencia', models.BooleanField(default=False)),
                ('es_agente', models.BooleanField(default=False)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representantes', to='stats.jugador')),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
                'db_table': 'representantes',
                'ordering': ['nombre'],
            },
        ),
    ]
